version: '3.8'

services:
  yle-bot:
    image: ghcr.io/ametysti/yle-bot:latest
    container_name: yle-bot
    depends_on:
      - redis
    environment:
      - TOKEN=
      - REDIS_URI=
      - HEARTBEAT_URL=
    deploy:
      restart_policy:
        condition: on-failure

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - 100.68.75.47:6413:6379
    volumes:
      - ./data/dragonfly:/data