version: '3.8'

services:
  yle-bot:
    image: ghcr.io/ametysti/yle-bot:latest
    container_name: yle-bot
    depends_on:
      - redis
    environment:
      - TOKEN=
      - REDIS_URI=
      - HEARTBEAT_URL=
    deploy:
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7
    container_name: yle-bot_redis
    restart: always
    ports:
      - '127.0.0.1:6413:6379'
      - '100.68.75.47:6413:6379'
    command: redis-server --save 20 1 --loglevel warning 
    volumes:
      - ./data/redis:/data